### ISSUE TITLE
Can't launch snap: error while loading shared libraries

### ISSUE THREAD

**Issue by EwanPolsUA** [nbuechner/openrct2-snap#1]
While opening the OpenRCT2 snap (v 0.4.12), the application crashes with the following error:

`/snap/openrct2-unofficial/17/usr/bin/openrct2: error while loading shared libraries: libvorbisfile.so.3: cannot open shared object file: No such file or directory
`

**Comment by nbuechner** [comment]
Please check if the latest update fixes this.

**Comment by EwanPolsUA** [comment]
Unfortunately, it does not. I now get the following message;
`xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/ewanpols/snap/openrct2-unofficial/common/.cache/gio-modules/libgiolibproxy.so
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Segmentation fault (core dumped)
`

**Comment by EwanPolsUA** [comment]
Issue is now solved after deleting the snap completely with `snap remove --purge` and reinstalling.
